/// Shared UI building blocks: theme tokens, base widgets and validators.
library;

export 'package:federfall/theme/app_spacing.dart';
export 'package:federfall/theme/app_theme.dart';

export 'app_sheet.dart';
export 'discard_guard.dart';
export 'form_sheet.dart';
export 'layout/content_bounds.dart';
export 'layout/list_detail_scaffold.dart';
export 'layout/window_size.dart';
export 'number_format.dart';
export 'validators.dart';
export 'widgets/app_text_field.dart';
export 'widgets/async_value_view.dart';
export 'widgets/attachment_kind.dart';
export 'widgets/breakdown_bars.dart';
export 'widgets/breakdown_card.dart';
export 'widgets/breakdown_pie.dart';
export 'widgets/cached_file_image.dart';
export 'widgets/date_field.dart';
export 'widgets/destructive_action_button.dart';
export 'widgets/destructive_dialog.dart';
export 'widgets/detail_header.dart';
export 'widgets/editable_photo_strip.dart';
export 'widgets/empty_view.dart';
export 'widgets/error_view.dart';
export 'widgets/icon_chip.dart';
export 'widgets/image_cropper.dart';
export 'widgets/image_viewer.dart';
export 'widgets/kpi_card.dart';
export 'widgets/loading_view.dart';
export 'widgets/map_attribution.dart';
export 'widgets/map_tile_layer.dart';
export 'widgets/map_wheel_zoom.dart';
export 'widgets/menu_action.dart';
export 'widgets/offline_notice.dart';
export 'widgets/paged_list_tail.dart';
export 'widgets/primary_button.dart';
export 'widgets/staged_photos.dart';
export 'widgets/tag_chip.dart';
